#!/usr/bin/env bash
# Update package index
# Install nginx
# Start nginx
# allowing nginx on firewall
# Give the user ownership to website files for easy editing
# Creating new index
# Restarting nginx

sudo apt-get update -y -qq
sudo apt-get install nginx -y
sudo service nginx start
sudo ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.html
sudo service nginx restart
