#!/usr/bin/env bash

# Update package index
sudo apt-get update -y -qq

# Install nginx
sudo apt-get install nginx -y

# Start nginx
sudo service nginx start

# allowing nginx on firewall
sudo ufw allow 'Nginx HTTP'

# Give the user ownership to website files for easy editing
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Creating new index
echo 'Hello World!' > /var/www/html/index.html

# Restarting nginx
sudo service nginx restart
