#!/usr/bin/env bash
# The redirection must be a “301 Moved Permanently”
# You answer file should be a Bash script containing commands
# to automatically configure a Ubuntu machine to respect above requirements
# Using what you did with 1-install_nginx_web_server,
# write 3-redirection so that it configures a brand
# new Ubuntu machine to the requirements asked in this task

sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start
sudo ufw allow 'Nginx HTTP'
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www
echo -e "Hello World!" | dd status=none of=/var/www/html/index.nginx-debian.html
sudo sed -i "30i \\\tlocation /redirect_me {\n\t\t return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n" /etc/nginx/sites-available/default
sudo service nginx restart
