#!/usr/bin/env bash
# The page must return an HTTP 404 error code
# The page must contain the string Ceci n'est pas une page
# Using what you did with 3-redirection,
# write 4-not_found_page_404 so that it configures a brand
# new Ubuntu machine to the requirements asked in this task

sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start
sudo ufw allow 'Nginx HTTP'
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www
echo -e "Hello World!" | dd status=none of=/var/www/html/index.nginx-debian.html
sudo sed -i "30i \\\tlocation /redirect_me {\n\t\t return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" >> /var/www/html/error_404.html
sudo sed -i '25i\	error_page 404 /error_404.html;' /etc/nginx/sites-available/default
sudo service nginx restart
