#!/usr/bin/env bash
# Script: 100-process_and_pid_file
# Description: 
# - Creates the file /var/run/myscript.pid containing its PID
# - Displays "To infinity and beyond" indefinitely
# - Displays "I hate the kill command" when receiving a SIGTERM signal
# - Displays "Y U no love me?!" when receiving a SIGINT signal
# - Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

cleanup() {
    echo "Cleaning up and terminating..."
    rm -f /var/run/myscript.pid
    exit
}

trap 'echo "I hate the kill command"; exit' SIGTERM
trap 'echo "Y U no love me?!"; exit' SIGINT
trap cleanup SIGQUIT SIGTERM

echo $$ > /var/run/myscript.pid

while true; do
    echo "To infinity and beyond"
    sleep 2
done
