#!/usr/bin/env bash
# Script: 67-stop_me_if_you_can
# Description: Kills the 7-highlander process without using kill or killall.
# Find and terminate the 7-highlander process

pid=$(pgrep -f "7-highlander")
if [ -n "$pid" ]; then
    echo "Terminating process..."
    kill -s SIGTERM "$pid"
else
    echo "Process not found"
fi
