#!/usr/bin/env bash
# Script: 7-highlander
# Description: Displays "To infinity and beyond" indefinitely with a sleep 2 in between each iteration.
#              Prints "I am invincible!!!" when receiving a SIGTERM signal.

pid=$(pgrep -f "7-highlander")
if [ -n "$pid" ]; then
    echo "Terminating process..."
    kill -s SIGTERM "$pid"
else
    echo "Process not found"
fi
