#!/usr/bin/env bash
# Script: 7-highlander
# Description: Displays "To infinity and beyond" indefinitely with a sleep 2 in between each iteration.
#              Prints "I am invincible!!!" when receiving a SIGTERM signal.

trap 'echo "I am invincible!!!"; exit' SIGTERM

while true; do
    echo "To infinity and beyond"
    sleep 2
done
