#!/usr/bin/env bash
# Script: 8-beheaded_process
# Description: Kills the process 7-highlander without using kill or killall.
# Find and terminate the 7-highlander process

pkill -f -SIGKILL 7-highlander
